### PR TITLE
UX improved 

### PR DESCRIPTION
**Pull request by rafsuntaskin**
Brought settings to popup to make changes on the fly.

### CODE REVIEW

**Comment by baybatu** [comment]
It would be cool to update extension image in README.md file for new users :)

**Comment by ufuk** [comment]
Thank you @rafsuntaskin. I will publish the new version on Chrome Web Store as soon as possible.

**Comment by ufuk** [comment]
By the way, I noticed that you are a CSGO player too. You can add me if you wish, my user name is "ufuli". 🔫 😃

**Comment by rafsuntaskin** [comment]
Hi @ufuk ,

Thanks to you first man, you saved me a lot of works , I was just thinking to build something like this for a few days and found this from you and I am so happy :D :D .

Take your time on publishing it to the chrome store, I have added another feature to hide meaning already and planning to add some other features as well. So, you may delay it so that you can publish it all together.

Glad to know you are a CSGO player too : 🔫  , I will add you when I get online ;)

**Comment by ufuk** [comment]
I look forward to new contributions and CSGO matches 😃 

Best

**Pull request merged**
